//<auto-generated>
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
using Snake.Client.Models;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;

var builder = WebAssemblyHostBuilder.CreateDefault(args);

await builder.Build().RunAsync();

// Add user secrets
builder.Configuration.AddUserSecrets<Program>();

// Register SqlConnector as a service
builder.Services.AddSingleton<SqlConnector>();

var app = builder.Build();